namespace: acm-prime-policies

resources:
  - banners
  - rbac
  - gitops-bootstrap
  - developer-hub
  - openshift-pipelines-operator
  - keycloak-operator
  - lvm-storage
  - devspaces
  - openshift-lightspeed
  - openshift-virtualization
  - kubeletconfig
  - rhacs-central
  - node-feature-discovery-operator
  - nvidia-gpu-operator
