namespace: costmanagement-metrics-operator

resources:
  - ../../base

patches:
  - patch: |-
      - op: replace
        path: /spec/source/name
        value: 'Lab - Prime'
    target:
      group: costmanagement-metrics-cfg.openshift.io
      version: v1beta1
      kind: CostManagementMetricsConfig
      name: costmanagementmetrics
      namespace: costmanagement-metrics-operator