apiVersion: operator.openshift.io/v1
kind: IngressController
metadata:
  name: default
  namespace: openshift-ingress-operator
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/sync-options: Validate=false,ServerSideApply=true
spec:
  defaultCertificate:
    name: apps-wildcard-cert
  # endpointPublishingStrategy:
  #     type: HostNetwork
  #     hostNetwork:
  #       protocol: PROXY
  #       httpPort: 80
  #       httpsPort: 443